"use client";

import { useEffect, useState } from "react";
import { Footer } from "../Component/Footer/Footer";
import { Navbar } from "../Component/Navbar/Navbar";

// export const metadata = {
//   title: "My Makan Home",
//   description: "Generated by create next app",
//   icons: {
//     icon: "/favicon.ico",
//     apple: "/favicon.ico",
//   },
// };

export default function Layout({ children }) {
  const [isSticky, setIsSticky] = useState(false);

  useEffect(() => {
    const handleScroll = () => {
      if (window.scrollY > 0.8) {
        setIsSticky(true);
      } else {
        setIsSticky(false);
      }
    };

    window.addEventListener("scroll", handleScroll);

    return () => {
      window.removeEventListener("scroll", handleScroll);
    };
  }, []);
  return (
    <html>
      <body>
        <div
          className={`${
            isSticky ? "bg-[#625dfaf3] sticky top-0 z-[200] py-4 lg:!py-0 backdrop-blur shadow" : "relative z-[200] bg-[#4A46FB] py-4 lg:!py-2 border-b-[1px] border-[#e6e6e6c2]"
          }`}
        >
          <Navbar />
        </div>
        <div>{children}</div>
        <Footer />
      </body>
    </html>
  );
}
