// export const siteUrl =
//   process.env.NEXT_PUBLIC_APP_URL || 'https://eco-bazar.vercel.app';

export const siteConfig = {
  name: "Eco Bazar",
  description: "My Makan Real Estate Site",
  // url: siteUrl,
  // ogImage: `${siteUrl}/opengraph-image.jpg`,
  keywords: [
    "nextjs",
    "react",
    "react server components",
    "tailwind",
    "shadcn/ui",
  ],
  cardData: [
    {
      title: "Dubai Appartment",
      total: 432,
      img: "./assets/images/dubai.png",
    },
    {
      title: "Horizon Tower",
      total: 450,
      img: "./assets/images/city1.jpg",
    },
    {
      title: "City Tower",
      total: 60,
      img: "./assets/images/city2.jpg",
    },
    {
      title: "Cornish Tower",
      total: 200,
      img: "./assets/images/city3.jpg",
    },
    {
      title: "Dubai Appartment",
      total: 140,
      img: "./assets/images/dubai.png",
    },
  ],
  agentFeeds: [
    {
      id: 1,
      name: "Maria Zara",
      property: "Fam Properties",
      des: "Available empty studio onthe 17th floor of Horizon Tower with a balcony is up for sale. It is 760 square feet in size and comes with parking for AED 220,000.",
    },
    {
      id: 2,
      name: "Hasan Ahmed",
      property: "Ajman Properties",
      des: "This 3-bed with a loft, 2-bath home in the gated community of The Hideout has it all. From the open floor plan to the abundance of light from the windows, this home is perfect for entertaining.",
    },
    {
      id: 3,
      name: "Rakib Mahmud",
      property: "United Properties",
      des: "You will love spending time on the deck taking in the beautiful views. In the kitchen, you'll find stainless steel appliances and a tile backsplash, as well as a breakfast bar.",
    },
    {
      id: 4,
      name: "Tanvir Ahmed",
      property: "Fam Properties",
      des: "Available empty studio onthe 17th floor of Horizon Tower with a balcony is up for sale. It is 760 square feet in size and comes with parking for AED 220,000.",
    },
  ],
  sellCards: [
    {
      id: 1,
      type: "Sell",
      price: "85,000",
      img: "./assets/images/home1.jpg",
      location: "Dubai",
      size: "1280 sqrt",
      bath: 4,
      bed: 8,
    },
    {
      id: 2,
      type: "Rent",
      price: "45,000",
      img: "./assets/images/home2.jpg",
      location: "Ajman",
      size: "780 sqrt",
      bath: 3,
      bed: 6,
    },
    {
      id: 3,
      type: "Sell",
      price: "90,500",
      img: "./assets/images/home3.jpg",
      location: "Abu Dabhi",
      size: "1600 sqrt",
      bath: 8,
      bed: 12,
    },
    {
      id: 4,
      type: "sell",
      price: "50,000",
      img: "./assets/images/home4.jpg",
      location: "Dubai",
      size: "1400 sqrt",
      bath: 4,
      bed: 6,
    },
    {
      id: 5,
      type: "Rent",
      price: "7,000",
      img: "./assets/images/home5.jpg",
      location: "Riyadh",
      size: "780 sqrt",
      bath: 2,
      bed: 4,
    },
    {
      id: 6,
      type: "Rent",
      price: "23,000",
      img: "./assets/images/home6.jpg",
      location: "Dubai",
      size: "800 sqrt",
      bath: 4,
      bed: 5,
    },
    {
      id: 7,
      type: "Sell",
      price: "9,000",
      img: "./assets/images/home1.jpg",
      location: "Abu Dabhi",
      size: "900 sqrt",
      bath: 5,
      bed: 6,
    },
    {
      id: 8,
      type: "Rent",
      price: "203,000",
      img: "./assets/images/home4.jpg",
      location: "Dubai",
      size: "2000 sqrt",
      bath: 8,
      bed: 14,
    },
    {
      id: 9,
      type: "Rent",
      price: "23,000",
      img: "./assets/images/home6.jpg",
      location: "Dubai",
      size: "800 sqrt",
      bath: 4,
      bed: 5,
    },
  ],
};
